version: '1.0'

services:
  jenkins:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: jenkins/jenkins:latest-jdk17
    container_name: jenkins-jdk17
    privileged: true
    user: root
    restart: always
    network_mode: bridge
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_home:
    name: jenkins_home
